import math


class MathUtils(object):
    phi = (1 + math.sqrt(5)) / 2
    phi_negative = (1 - math.sqrt(5)) / 2

    @staticmethod
    def gaussian_sum(number: int) -> float:
        return (number * (number + 1)) / 2

    @staticmethod
    def sum_of_digits(number: str) -> int:
        return sum([int(i) for i in number])

    @staticmethod
    def sum_of_digits(number: int) -> int:
        return sum([int(i) for i in str(number)])

    @staticmethod
    def fibonacci(start: tuple = (0, 1)):
        """
        The Fibonacci numbers are generated by setting F(0) = 0, F(1) = 1, and then using the recursive formula:

                F(n) = F(n-1) + F(n-2)

        Thus the sequence begins: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, … .
        """
        prev, curr = start

        while True:
            yield curr
            nxt = prev + curr
            prev = curr
            curr = nxt

    @staticmethod
    def nth_fibonacci(n: int) -> int:
        """
        Returns the n-th number of the Fibonacci sequence.

        a(n) = [φ^n – (-1/φ)^n] / Sqrt[5]

        φ == phi == golden ratio == 1.618033... == (1 + Sqrt[5]) / 2
        """
        return int((pow(MathUtils.phi, n) - pow(MathUtils.phi_negative, n)) / math.sqrt(5))

    @staticmethod
    def is_perfect_square(n: int) -> bool:
        """
        Returns True if the provided number is a
        perfect square (and False otherwise).
        """
        return math.isqrt(n) ** 2 == n

    @staticmethod
    def is_palindrome(n: int) -> bool:
        """Checks if the given number is a palindrome."""
        return str(n) == str(n)[::-1]

    @staticmethod
    def primes_sieve_of_eratosthenes(limit):
        """
        Sieve of Eratosthenes

        Finding all prime numbers up to any given limit.
        """
        a = [True] * limit  # Initialize the primality list
        a[0] = a[1] = False

        for (i, isprime) in enumerate(a):
            if isprime:
                yield i
                for n in range(i * i, limit, i):  # Mark factors non-prime
                    a[n] = False

    @staticmethod
    def is_prime(n):
        """Primality test using 6k+-1 optimization."""
        if n <= 3:
            return n > 1
        if not n % 2 or not n % 3:
            return False
        i = 5
        stop = int(n ** 0.5)
        while i <= stop:
            if not n % i or not n % (i + 2):
                return False
            i += 6
        return True

    @staticmethod
    def prime_factors(n):
        """Returns all prime factors for the given number."""
        i = 2
        factors = []
        while i * i <= n:
            if n % i:
                i += 1
            else:
                n //= i
                factors.append(i)
        if n > 1:
            factors.append(n)
        return factors

    @staticmethod
    def divisors(n):
        """Returns a sorted list of all divisors for the given number."""
        divs = [1]
        for i in range(1, int(math.sqrt(n)) + 1):
            if n % i == 0:
                divs.extend([i, n // i])
        divs.append(n)
        return sorted(list(set(divs)))
